import type { Metadata } from 'next';
import './globals.css';
import MainLayout from '@/components/templates/MainLayout';

export const metadata: Metadata = {
  title: 'EduSongs streaming App',
  description: 'Generated by Edusongs',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
