import type { Metadata } from "next";
import { useEffect, useState } from "react";
import "./globals.css";
import NavBar from "@/components/organisms/NavBar";
import Footer from "@/components/organisms/Footer";
import { Suspense } from "react";
import ClientLayout from "@/components/templates/ClientLayout";
import MainLayout from "@/components/templates/MainLayout";

export const metadata: Metadata = {
  title: "EduSongs streaming App",
  description: "Generated by Edusongs",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <ClientLayout> */}
        <MainLayout>
          <div className="">{children}</div>
          {/* </ClientLayout> */}
        </MainLayout>
      </body>
    </html>
  );
}
